# Generated by Django 2.2.1 on 2019-05-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s_name', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('credit_card', models.CharField(max_length=20)),
                ('qiwi_card', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('my_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('my_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='My_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('ship_date', models.DateField()),
                ('item_count', models.IntegerField()),
                ('transportation_cost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('my_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('my_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Delivery')),
                ('my_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store')),
            ],
        ),
        migrations.CreateModel(
            name='My_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('added_date', models.DateField()),
                ('my_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('my_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='my_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.AddField(
            model_name='city',
            name='my_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AddField(
            model_name='category',
            name='my_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
    ]
