# Generated by Django 2.2.1 on 2019-05-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='my_store',
        ),
    ]
